apriltag:                 # node name
  ros__parameters:
    # setup (defaults)
    image_transport: compressed  # image format: "raw" or "compressed"
    family: 16h5         # tag family name: 16h5, 25h9, 36h11
    size: 0.028             # default tag edge size in meters 
    # size: 1.0             # default tag edge size in meters 
    profile: false        # print profiling information to stdout

    # tuning of detection (defaults)
    max_hamming: 0        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: true        # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: false            # write additional debugging images to current working directory

    pose_estimation_method: "pnp" # method for estimating the tag pose

    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]          # tag IDs for which to publish transform (all 16h5 tags)
      frames: [apriltag_16h5_id_0, apriltag_16h5_id_1, apriltag_16h5_id_2, apriltag_16h5_id_3, apriltag_16h5_id_4, apriltag_16h5_id_5, apriltag_16h5_id_6, apriltag_16h5_id_7, apriltag_16h5_id_8, apriltag_16h5_id_9, apriltag_16h5_id_10, apriltag_16h5_id_11, apriltag_16h5_id_12, apriltag_16h5_id_13, apriltag_16h5_id_14, apriltag_16h5_id_15, apriltag_16h5_id_16, apriltag_16h5_id_17, apriltag_16h5_id_18, apriltag_16h5_id_19, apriltag_16h5_id_20, apriltag_16h5_id_21, apriltag_16h5_id_22, apriltag_16h5_id_23, apriltag_16h5_id_24, apriltag_16h5_id_25, apriltag_16h5_id_26, apriltag_16h5_id_27, apriltag_16h5_id_28, apriltag_16h5_id_29]          # frame names with family and ID
      # sizes:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]          # tag-specific edge size, overrides the default 'size'
